### ISSUE TITLE
Deploy registry cron to update the latest registry index

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/cloud-tasks#59] opened 2022-11-30 17:59 UTC
## 💡 Description

See ticket https://github.com/nasa-pds/pds-api/issues/221

**Comment by tloubrieu-jpl** [comment] 2023-02-23 21:36
This ticket is a duplicate of its EPIC...

**Comment by jordanpadams** [comment] 2023-02-23 22:58
duplicate of https://github.com/nasa-pds/registry/issues/141

**Closed by jordanpadams** 2023-02-23 22:58 UTC
Labels: B13.1, sprint-backlog, task, i&t.skip
